### ISSUE TITLE
Enable GithubPages on the Piano repo to publish piano.html on the web

### ISSUE THREAD

**Issue by sEver** [MargoKrk/Piano#1]
Top repo menu -> Settings.
Left menu -> Pages
Source -> Deploy from branch
Branch -> ~~Master~~ **main**
Directory -> Root
Save

**Comment by sEver** [comment]
Be advised, it might be required to rename Piano.html to index.html, OR create a new index.html file that will present Piano.html, as GithubPages will be looking for index.html file to serve.

**Comment by sEver** [comment]
@MargoKrk please use branch `main`, we've updated task description.

**Comment by MargoKrk** [comment]
Done
