### ISSUE TITLE
P-007 Make the keyboard larger, so its width covers almost entire table

### ISSUE THREAD

**Issue by MargoKrk** [MargoKrk/Piano#12]
There are many ways to do it.

You can check:
`transform: scale(1.6)`
or change height/width of keys to percents (of the height/width of the parent container).

**Comment by MargoKrk** [comment]
Musiałam to zmienić na issue bo w drafcie nie mogłam zostawić komentarza.
Jeśli używam transform to działa nieźle ale nie stosuje mi się do display-flex-end nałożonego na PianoTable i trochę się rozjeżdża BlackKeyLayer. 
Jak zrobić procenty z rodzica, jeśli rodzic jest vw? Wyskakuje mi invalid property value.

**Comment by MargoKrk** [comment]
I pushed commented proposal for changes without transform:scale. It's changes width/height for black or white keys and keys leyers by hand.

**Comment by sEver** [comment]
If we know the width of the parent in VW ( `80vw` in this case ), we can use:
8vw as 1/10th of a parent (10%), 
4vw as 1/20th (5%), 
etc.

**Comment by sEver** [comment]
We can use the `width: 2.5%;` on a key as usual. 
"Invalid property value" indicates a typo.
If added properly, It might interact with the flexbox-given dimensions, but should work. 
See width below:

![image](https://user-images.githubusercontent.com/8565038/204417049-15c00395-1b2a-44e0-aeba-d87e7240171c.png)
